# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Richard Goulter's GitHub Pages
tagline:          'NUS CS Undergrad'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://rgoulter.github.io

author:
  name:           'Richard Goulter'
  url:            https://twitter.com/rgoulter

paginate:         1

# Custom vars

github:
  repo:           https://github.com/rgoulter/rgoulter.github.com
